jwt:
  secret: 'K#7g!Lp$2*T@R&5f'



server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    password: password
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
